version: "3.8"
services:
  notebooks:
    build: .
    ports:
      - "8001:8888"
    volumes:
      - type: bind
        source: ./notebooks
        target: /home/jovyan/work
      - type: bind
        source: ./data
        target: /home/jovyan/data